language: python # Need python environment for pip

sudo: false # Use container-based infrastructure

env:
  - LUA="lua=5.1"
  - LUA="lua=5.2"
  - LUA="lua=5.3"
  - LUA="luajit=2.0"
  - LUA="luajit=2.1"

before_install:
  - pip install hererocks
  - hererocks lua_install --luarocks ^ --$LUA --compat none
  - export PATH=$PATH:$PWD/lua_install/bin
  - luarocks install luasocket 3.0rc1-2
  - luarocks install luasec --server=https://luarocks.org/manifests/ignacio OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
  - luarocks install luacov
  - luarocks install luacov-coveralls

install:
  - luarocks install lunitx

script:
  - cd unittest
  - lua -lluacov run.lua

after_success:
  - luacov-coveralls -v -r .. -e ../lua_install -o test.json
  - cat test.json
